- name: install required packages
  apt: name="{{item}}" state=present
  with_items:
  - apache2 
  - apache2-utils 
  - python
  - git
  - libapache2-mod-wsgi
  - python-flask
  - python-flask-sqlalchemy
  - python-dateutil
  - postgresql
  - python-psycopg2

- name: enable apache2 modules
  raw: a2enmod {{ item }}
  with_items:
  - ssl 

- name: create /opt/ 
  file: path="/opt/" state=directory

- name: checkout repository
  git: repo=git@gitlab.ctrdn.net:cerise/cerise-controller.git
       dest=/opt/cerise-controller
       accept_hostkey=yes

