
- name: install bacula-fd
  apt: name=bacula-fd state=present

- name: configure bacula-fd
  template: src="bacula-fd.conf" dest="/etc/bacula/bacula-fd.conf"

- name: copy keys and certificates
  copy: dest="/etc/bacula/{{item.dst}}" src="backup/{{backup_group}}/{{item.src}}" owner="root" group="root" mode=0750
  with_items:
  - { src: "{{backup_host}}.crt", dst: "{{backup_host}}.crt" }
  - { src: "{{backup_host}}.pem", dst: "{{backup_host}}.pem" }
  - { src: "ca.crt", dst: "ca.crt" }

- name: copy mysql backup script
  copy: dest="/etc/bacula/scripts/make_mysql_backup.sh" src="make_mysql_backup.sh" owner="root" group="root" mode=0750

- name: restart bacula-fd
  service: name=bacula-fd state=restarted

