- name: install required packages
  apt: name="{{item}}" state=present
  with_items:
  - python-pip
  - openvswitch-switch
  - dnsmasq
  - openvpn
  - git

- name: checkout repository
  git: repo=git@gitlab.ctrdn.net:cerise/cerise-endpoint.git
       dest=/opt/cerise-endpoint

- name: install pip dependencies
  pip: chdir="opt/cerise-endpoint" requirements="requirements.txt"

- name: create cache
  file: path="/var/cache/cerise-endpoint/" state=directory


