- name: install packages
  apt: name={{ item }}
  with_items:
  - apache2 
  - apache2-utils 
  - php5 
  - php5-common 
  - php5-fpm 
  - php5-gd 
  - php5-cli 
  - libapache2-mod-fastcgi 
  - php-auth 
  - php5-mcrypt 
  - mcrypt 
  - php5-imagick 
  - imagemagick 
  - php5-curl 
  - php5-intl 
  - php5-memcache 
  - php5-memcached 
  - php5-ming 
  - php5-ps 
  - php5-pspell 
  - php5-recode 
  - php5-sqlite 
  - php5-tidy 
  - php5-xmlrpc 
  - php5-xsl 
  - memcached 

- name: enable php5 modules
  raw: php5enmod {{ item }}
  with_items:
  - mcrypt

- name: enable apache2 modules
  raw: a2enmod {{ item }}
  with_items:
  - rewrite 
  - ssl 
  - actions 
  - include 
  - dav_fs 
  - dav 
  - auth_digest 
  - actions 
  - fastcgi 
  - alias

- name: configure apache2 
  copy: src="{{ item }}" dest="/etc/apache2/conf-available/{{ item }}"
  with_items:
  - php5-fpm.conf
  - ssl.conf

- name: configure apache default sites 
  copy: src="000-default.conf" dest="/etc/apache2/sites-available/000-default.conf"

- name: delete unused files
  file: path="{{ item }}" state=absent
  with_items:
  - "/var/www/html/index.html"
  - "/etc/apache2/sites-available/default-ssl.conf"

- name: enable apache2 configs
  raw: a2enconf {{ item }}
  with_items:
  - php5-fpm

#- name: disable docs
#  raw: a2disconf apache2-doc

- name: disable autoindex
  raw: a2dismod autoindex

- name: change apache security.conf
  lineinfile: 
    dest: "/etc/apache2/conf-enabled/security.conf"
    line: "{{ item }}"
  with_items:
  - "ServerTokens Prod"
  - "ServerSignature Off"

- name: restart apache2
  service: name=apache2 state=restarted

- name: restart php5-fpm
  service: name=php5-fpm state=restarted

