- name: install packages
  apt: name={{ item }}
  with_items:
  - apache2 
  - apache2-utils 
  - libapache2-mod-fastcgi 
  - php-fpm 
  - php-cli 
  - php-curl 
  - php-mcrypt
  - php-mbstring
  - php-gettext
  - php-gd 
  - php-zip 
  - php-imagick 
  - imagemagick 
  - composer

- name: enable php modules
  raw: phpenmod {{ item }}
  with_items:
  - mcrypt
  - mbstring

- name: enable apache2 modules
  raw: a2enmod {{ item }}
  with_items:
  - rewrite 
  - ssl 
  - actions 
  - include 
  - auth_digest 
  - actions 
  - fastcgi 
  - alias
  - vhost_alias  

- name: configure apache2 
  copy: src="{{ item }}" dest="/etc/apache2/conf-available/{{ item }}"
  with_items:
  - php-fpm.conf
  - ssl.conf

- name: configure apache default sites 
  copy: src="000-default.conf" dest="/etc/apache2/sites-available/000-default.conf"

- name: delete unused files
  file: path="{{ item }}" state=absent
  with_items:
  - "/var/www/html/index.html"
  - "/etc/apache2/sites-available/default-ssl.conf"
  - "/etc/apache2/sites-available/default-tls.conf"

- name: enable apache2 configs
  raw: a2enconf {{ item }}
  with_items:
  - php-fpm

- name: disable mod_php 
  raw: a2dismod php*
  ignore_errors: yes

- name: disable mod_php 
  raw: a2dismod php7.0
  ignore_errors: yes

- name: disable mod_php 
  raw: a2dismod php7.1
  ignore_errors: yes

#- name: disable docs
#  raw: a2disconf apache2-doc

- name: disable autoindex
  raw: a2dismod autoindex -f

- name: change apache security.conf
  lineinfile: 
    dest: "/etc/apache2/conf-enabled/security.conf"
    line: "{{ item }}"
  with_items:
  - "ServerTokens Prod"
  - "ServerSignature Off"

- name: restart apache2
  service: name=apache2 state=restarted

- name: restart php-fpm
  service: name=php7.0-fpm state=restarted

