# make sure sudo group is existing
- name: add sudo group
  group: name=sudo state=present

# create users as specified in users var
- name: create user
  user: 
    name={{ item }} 
    shell=/bin/bash 
    state=present 
    groups=sudo,adm
    createhome=yes
  with_items : "{{ users }}"

# install public ssh keys (authorized_keys)
- name: add authorized_keys
  authorized_key: 
    user={{ item }} 
    state=present 
    key="{{ lookup('file', './files/ssh-keys/'+item) }}"
  with_items : "{{ users }}"
