- name: install ntp
  apt: name=ntp

- name: install datentp
  apt: name=ntpdate

- name: stop ntp
  service: name=ntp state=stopped
- name: syncronize time
  command: ntpdate pool.ntp.org

- name: configure ntpd
  lineinfile: 
    dest: "/etc/ntp.conf" 
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
  - { regexp: '^pool 0.pool.ntp.org', line: 'pool 0.pool.ntp.org burst iburst' }
  - { regexp: '^pool 1.pool.ntp.org', line: 'pool 1.pool.ntp.org burst iburst' }
  - { regexp: '^pool 2.pool.ntp.org', line: 'pool 2.pool.ntp.org burst iburst' }
  - { regexp: '^pool 3.pool.ntp.org', line: 'pool 3.pool.ntp.org burst iburst' }
  - { regexp: '^pool europe.pool.ntp.org', line: 'pool europe.pool.ntp.org burst iburst' }

- name: start ntp
  service: name=ntp state=restarted
