- hosts: relay1.netvor.sk relay2.netvor.sk
  roles:
  - linux-server
  - { role: admins, users: ['johnny'] }
  - virtual
  - swap
  - letsencrypt
  - mail-antispam
    #- backup-client
    #- monitor-client
    #- firewall
