- hosts: tmgh.hrdlica.cz
  vars:
    user: johnny
  roles:
  - ubuntu_server
  - { role: admins, users: ['johnny','peter'] }
  - www
  - letsencrypt
  - firewall
  - mail-stub
  - mail-admin
  - monitor-client
  - backup-client
