- hosts: netvor binarity szsbaza verde hrdlica
  tasks:
  - name: apt-get update
    apt: update_cache=yes
  - name: apt-get upgrade
    apt: upgrade=safe
    register: upgrade
  - name: apt-get upgrade results
    debug: var=upgrade
  - name: apt-get dist-upgrade
    apt: upgrade=dist
    register: dist_upgrade
  - name: apt-get dist-upgrade results
    debug: var=dist_upgrade
  - name: apt-get autoremove
    command: apt-get -y autoremove

