- name: install ns packages
  apt: name={{item}}
  with_items:
  - bind9
  - bind9utils

- name: configure bind
  template: 
      src="{{item}}"
      dest="/etc/bind/{{item}}"
  with_items:
  - named.conf.local
  - named.conf.options

- name: prepare directories
  file:
      path="{{item}}"
      state=directory
      owner=bind group=bind mode=750
  with_items:
  - "/etc/bind/master/"
  - "/opt/netvor/"

- name: install generate.js 
  copy:
      src="generate.js"
      dest="/opt/netvor/generate_bind.js"
      owner=bind group=bind mode=750

- name: create generate.js configuration file
  template:
      src="config.json"
      dest="/opt/netvor/config.json"
      owner=bind group=bind mode=600

- name: install npm dependencies
  npm:
      name="{{item}}"
      path="/opt/netvor/"
  with_items:
  - dateformat
  - q
  - request
  - nconf

- name: restart bind
  service: 
      name=bind9
      state=restarted

