- name: install build dependencies
  apt: name={{ item }}
  with_items:
  - build-essential
  - libpcap-dev
  - libgeoip-dev

- name: create stats directory
  file:
    path=/var/lib/ccstat
    state=directory
    owner=nobody group=nogroup mode=750

- name: create install directory
  file:
    path=/usr/local/bin/
    state=directory
    owner=root group=root mode=755

- name: create build directory
  file:
    path=/tmp/ccstat/
    state=directory
    owner=root group=root mode=750

- name: copy build files over 
  copy:
    src=../../ccstat/{{ item }}
    dest=/tmp/ccstat/{{ item }}
  with_items:
  - stdafx.c
  - stdafx.h
  - Makefile
  - ccstat.c

- name: build project
  command: make
    chdir=/tmp/ccstat

- name: install ccstat
  copy: 
    src=/tmp/ccstat/ccstat 
    dest=/usr/local/bin/ccstat
    remote_src=True
    owner=root group=root mode=755

- name: install support scripts
  template:
    src=../../ccstat/{{ item }}
    dest=../../usr/local/bin/{{ item }}
    owner=root group=root mode=750
  with_items:
  - ccstat_email_totals
  - ccstat_print_totals
  - ccstat_rotate
  - ccstat_total

- name: create cron job
  copy:
    src=../../ccstat/cron.conf
    dest=/etc/cron.d/ccstat.conf
    owner=root group=root mode=640

- name: restart cron service
  service: 
    name=cron
    state=restarted

